name: 'Install Package'
description: 'Install system packages from brew, brew cask, apt and choco.'
branding:
  icon: package
  color: blue
inputs:
  brew:
    description: Packages to install with brew on macOS
    required: false
    default: ''
  brew-cask:
    description: Packages to install with brew cask on macOS
    required: false
    default: ''
  apt:
    description: Packages to install with apt on Linux
    required: false
    default: ''
#  yum:
#    description: Packages to install with yum inside Docker on Linux
#    required: false
#    default: ''
  choco:
    description: Packages to install with choco on Windows
    required: false
    default: ''
  pacman-mingw64:
    description: Packages to install with pacman on Windows
    required: false
    default: ''
  pacman-mingw32:
    description: Packages to install with pacman on Windows
    required: false
    default: ''
  pacman-ucrt64:
    description: Packages to install with pacman on Windows
    required: false
    default: ''
  pacman-clang64:
    description: Packages to install with pacman on Windows
    required: false
    default: ''
runs:
  using: "composite"
  steps:

    - name: Install brew packages
      if: runner.os == 'macOS' && inputs.brew != ''
      run: |
        brew update
        echo "${{ inputs.brew }}" | xargs -n 1 brew install
      shell: sh

    - name: Install brew cask packages
      if: runner.os == 'macOS' && inputs.brew-cask != ''
      run: |
        brew update
        echo "${{ inputs.brew-cask }}" | xargs -n 1 brew install --cask
      shell: sh

    - name: Install apt packages
      if: runner.os == 'Linux' && inputs.apt != ''
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt }}
      shell: sh

    - name: Install choco packages
      if: runner.os == 'Windows' && inputs.choco != ''
      run: choco install -y ${{ inputs.choco }}
      shell: sh

    - name: Install pacman packages (mingw64)
      if: runner.os == 'Windows' && inputs.pacman-mingw64 != ''
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: ${{ inputs.pacman-mingw64 }}

    - name: Install pacman packages (mingw32)
      if: runner.os == 'Windows' && inputs.pacman-mingw32 != ''
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: ${{ inputs.pacman-mingw32 }}

    - name: Install pacman packages (ucrt64)
      if: runner.os == 'Windows' && inputs.pacman-ucrt64 != ''
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: ${{ inputs.pacman-ucrt64 }}

    - name: Install pacman packages (clang64)
      if: runner.os == 'Windows' && inputs.pacman-clang64 != ''
      uses: msys2/setup-msys2@v2
      with:
        update: true
        msystem: mingw64
        install: ${{ inputs.pacman-clang64 }}
