# This workflow is used to test the action

on:
  push:
  pull_request:

jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          brew: hello yq
          brew-cask: MacVim
          apt: rolldice bcal
          choco: graphviz less
  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: ./
      with:
        brew: hello yq
        brew-cask: MacVim
        apt: rolldice bcal
        choco: graphviz less
  windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
    - uses: ./
      with:
        brew: hello yq
        brew-cask: MacVim
        apt: rolldice bcal
        choco: graphviz less
